name: a_village
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/splashscreen_logo.png
    - assets/images/englishlang_logo.png
    - assets/images/arrow.png
    - assets/images/chineselang_logo.png
    - assets/images/nextbutton.png
    - assets/images/app_logo.png
    - assets/images/email.png
    - assets/images/password.png
    - assets/images/eye.png
    - assets/images/googlelogo.png
    - assets/images/applelogo.png
    - assets/images/user.png
    - assets/images/userlogo.png
    - assets/images/mobile.png
    - assets/images/backarrowicon.png

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Bold.ttf
        - asset: assets/fonts/InterTight-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
